services:
  web:
    build: .
    volumes:
      - .:/app
    command: gunicorn eternal.wsgi:application --bind 0.0.0.0:8000 --workers 2  # Отключен авторелоад
    depends_on:
      - db
    expose:
      - "8000"
    
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: butch_db
      POSTGRES_USER: butch
      POSTGRES_PASSWORD: butch
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static  # Статика Django
    depends_on:
      - web

volumes:
  postgres_data: